minimumReleaseAgeExclude:
  - '@magicvr/schema-ui-protocol@0.2.0'
  - '@magicvr/schema-ui-renderer@0.1.0 || 0.2.0'
  - '@magicvr/schema-ui-lib@0.1.0'
  - '@magicvr/schema-ui-shell@0.1.0'
  - '@magicvr/schema-ui-theme@0.1.0'
  - '@magicvr/schema-ui-ui@0.1.0'
